#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
#

version: 2.1

executors:
  daml-executor:
    docker:
      - image: circleci/openjdk:11.0-jdk

jobs:
  mvn_test:
    executor: daml-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2
      - run:
          command: |
            curl -sSL https://get.daml.com/ | sh
            export PATH=/home/circleci/.daml/bin:$PATH
            mvn verify
      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports
  daml_test:
    executor: daml-executor
    steps:
      - checkout
      - run:
          command: |
            mkdir -p target/daml-test-reports
            curl -sSL https://get.daml.com/ | sh
            /home/circleci/.daml/bin/daml build -o target/supplychain.dar
            /home/circleci/.daml/bin/daml test --junit target/daml-test-reports/daml-test.xml src/main/daml/DA/RefApps/SupplyChain/Scenarios.daml
      - store_test_results:
          path: target/daml-test-reports
      - store_artifacts:
          path: target/daml-test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - daml_test
      - mvn_test
