#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
#

version: 2.1

executors:
  daml-executor:
    docker:
      - image: circleci/openjdk:11.0-jdk

jobs:
  mvn_test:
    executor: daml-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}-{{ checksum "daml.yaml" }}
            - m2
      - run:
          command: |
            wget https://github.com/digital-asset/daml/releases/download/v0.12.20/daml-sdk-0.12.20-linux.tar.gz
            tar -zxvf daml-sdk-0.12.20-linux.tar.gz
            cd sdk-0.12.20
            ./install.sh
            cd -
            rm -rf sdk-0.12.20
            export PATH=/home/circleci/.daml/bin:$PATH
            mvn verify
      - save_cache:
          paths:
            - ~/.m2
            - ~/.daml
          key: m2-{{ checksum "pom.xml" }}-{{ checksum "daml.yaml" }}
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports
  daml_test:
    executor: daml-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - daml-{{ checksum "daml.yaml" }}
      - run:
          command: |
            mkdir -p target/daml-test-reports
            wget https://github.com/digital-asset/daml/releases/download/v0.12.20/daml-sdk-0.12.20-linux.tar.gz
            tar -zxvf daml-sdk-0.12.20-linux.tar.gz
            cd sdk-0.12.20
            ./install.sh
            cd -
            /home/circleci/.daml/bin/daml build -o target/supplychain.dar
            /home/circleci/.daml/bin/daml test --junit target/daml-test-reports/daml-test.xml src/main/daml/DA/RefApps/SupplyChain/Scenarios.daml
      - save_cache:
          paths:
            - ~/.daml
          key: daml-{{ checksum "daml.yaml" }}
      - store_test_results:
          path: target/daml-test-reports
      - store_artifacts:
          path: target/daml-test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - daml_test
      - mvn_test
